language: python
python:
  - '3.6'
install:
  - git describe --tags > uw_saml2/VERSION
  - sudo apt-get update -qq
  - sudo apt-get install -qq libxmlsec1-dev
  - pip install -U -e .[test]
  - pip install coveralls
script:
  - pycodestyle .
  - pytest --cov uw_saml2
after_success:
  - coveralls
deploy:
  skip_cleanup: true
  provider: script
  script: pip install twine && python setup.py sdist && twine upload dist/*
  on:
    tags: true
