language: python
python:
  - "3.6"
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libxmlsec1-dev
  - pip install -U -e .[test]
  - pip install coveralls
script:
  - pycodestyle .
  - pytest --cov uw_saml2
after_success:
  - coveralls
