name: Release new version of uw-saml-python

on:
  push:
    branches:
      - main
      - test-release-workflow

env:
  workflow_url: >
    https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
  dry_run: ${{ github.ref != 'refs/heads/main' }}
  GCLOUD_TOKEN: ${{ secrets.GCR_TOKEN }}

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
      - with:
          project_id: ${{ secrets.IAM_GCR_REPO }}
          service_account_key: ${{ env.GCLOUD_TOKEN }}
          export_default_credentials: true
        uses: google-github-actions/setup-gcloud@v0.2.1

      - run: |
          echo "::set-output name=version::$(poetry version -s)"
          echo "::set-output name=short-sha::${GITHUB_SHA:0:10}"
        id: configure

      - run: ./scripts/pre-push.sh --check-only
        id: run-tests

      - uses: ncipollo/release-action@v1.8.6
        if: ${{ ! env.dry_run }}
        id: create-release
        with:
          token: ${{ github.token }}
          commit: ${{ github.sha }}
          tag: ${{ steps.configure.outputs.version }}

      - run: |
          set -x
          poetry publish \
            --build \
            $(test "${{ env.dry_run }}" == "false" || echo "--dry-run")
        id: publish-release